import "./globals.css";

import { ThemeProvider } from "@/components/theme/theme-provider";

export const metadata = {
  title: "Create Better Next",
  description: "Generated by Create Better Next."
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
